using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FaithFlow.Backend.Migrations
{
    /// <inheritdoc />
    public partial class FixRequestCommentsPostgresIdentity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // RequestComments was scaffolded for SQLite only; production Postgres
            // created "Id" without a sequence/identity, so inserts fail with null Id.
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_attribute a
                            JOIN pg_class c ON a.attrelid = c.oid
                            JOIN pg_namespace n ON c.relnamespace = n.oid
                            WHERE c.relname = 'RequestComments'
                              AND n.nspname = current_schema()
                              AND a.attname = 'Id'
                              AND a.attidentity IN ('a', 'd')
                        ) THEN
                            ALTER TABLE "RequestComments"
                                ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
                        END IF;
                    END $$;
                    """);
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql(
                    """
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM pg_attribute a
                            JOIN pg_class c ON a.attrelid = c.oid
                            JOIN pg_namespace n ON c.relnamespace = n.oid
                            WHERE c.relname = 'RequestComments'
                              AND n.nspname = current_schema()
                              AND a.attname = 'Id'
                              AND a.attidentity IN ('a', 'd')
                        ) THEN
                            ALTER TABLE "RequestComments"
                                ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;
                        END IF;
                    END $$;
                    """);
            }
        }
    }
}
