// <auto-generated />
using System;
using System.Collections.Generic;
using FaithFlow.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaithFlow.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260706163335_AddNotificationsAndDepartments")]
    partial class AddNotificationsAndDepartments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaithFlow.Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Handles prayer and pastoral care requests.",
                            Name = "Chaplain Services"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Handles ride and transport requests.",
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Handles supply and materials requests.",
                            Name = "Supply & Logistics"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Handles service, maintenance, and labor requests.",
                            Name = "Facilities"
                        });
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.DepartmentRequestType", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("integer");

                    b.HasKey("DepartmentId", "RequestTypeId");

                    b.HasIndex("RequestTypeId");

                    b.ToTable("DepartmentRequestTypes");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            RequestTypeId = 2
                        },
                        new
                        {
                            DepartmentId = 2,
                            RequestTypeId = 1
                        },
                        new
                        {
                            DepartmentId = 3,
                            RequestTypeId = 3
                        },
                        new
                        {
                            DepartmentId = 4,
                            RequestTypeId = 4
                        },
                        new
                        {
                            DepartmentId = 4,
                            RequestTypeId = 5
                        });
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int>("PrayerId")
                        .HasColumnType("integer");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrayerId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Prayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnsweredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PrayerDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("integer");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("RequesterEmail")
                        .HasColumnType("text");

                    b.Property<int>("StreakDays")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoiceNoteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestTypeId");

                    b.ToTable("Prayers");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.ProgressNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MoodRating")
                        .HasColumnType("integer");

                    b.Property<int>("PrayerId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrayerId");

                    b.ToTable("ProgressNotes");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.RequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("RequestTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ride"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Prayer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Supply"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Service"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Labor"
                        });
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.UserDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("UserDepartments");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.DepartmentRequestType", b =>
                {
                    b.HasOne("FaithFlow.Backend.Models.Department", "Department")
                        .WithMany("DepartmentRequestTypes")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaithFlow.Backend.Models.RequestType", "RequestType")
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Notification", b =>
                {
                    b.HasOne("FaithFlow.Backend.Models.Prayer", "Prayer")
                        .WithMany()
                        .HasForeignKey("PrayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prayer");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Prayer", b =>
                {
                    b.HasOne("FaithFlow.Backend.Models.RequestType", "RequestType")
                        .WithMany("Prayers")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.ProgressNote", b =>
                {
                    b.HasOne("FaithFlow.Backend.Models.Prayer", "Prayer")
                        .WithMany("ProgressNotes")
                        .HasForeignKey("PrayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prayer");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.UserDepartment", b =>
                {
                    b.HasOne("FaithFlow.Backend.Models.Department", "Department")
                        .WithMany("Members")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Department", b =>
                {
                    b.Navigation("DepartmentRequestTypes");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Prayer", b =>
                {
                    b.Navigation("ProgressNotes");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.RequestType", b =>
                {
                    b.Navigation("Prayers");
                });
#pragma warning restore 612, 618
        }
    }
}
