// <auto-generated />
using System;
using System.Collections.Generic;
using FaithFlow.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaithFlow.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260703141756_AddRequestType")]
    partial class AddRequestType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaithFlow.Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Prayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnsweredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PrayerDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("StreakDays")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoiceNoteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestTypeId");

                    b.ToTable("Prayers");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.ProgressNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MoodRating")
                        .HasColumnType("integer");

                    b.Property<int>("PrayerId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrayerId");

                    b.ToTable("ProgressNotes");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.RequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("RequestTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ride"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Prayer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Supply"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Service"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Labor"
                        });
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Prayer", b =>
                {
                    b.HasOne("FaithFlow.Backend.Models.RequestType", "RequestType")
                        .WithMany("Prayers")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.ProgressNote", b =>
                {
                    b.HasOne("FaithFlow.Backend.Models.Prayer", "Prayer")
                        .WithMany("ProgressNotes")
                        .HasForeignKey("PrayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prayer");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Prayer", b =>
                {
                    b.Navigation("ProgressNotes");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.RequestType", b =>
                {
                    b.Navigation("Prayers");
                });
#pragma warning restore 612, 618
        }
    }
}
