// <auto-generated />
using System;
using FaithFlow.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaithFlow.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260707173742_RenameDepartmentsToGroups")]
    partial class RenameDepartmentsToGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("FaithFlow.Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Handles prayer and pastoral care requests.",
                            Name = "Chaplain Services"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Handles ride and transport requests.",
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Handles supply and materials requests.",
                            Name = "Supply & Logistics"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Handles service, maintenance, and labor requests.",
                            Name = "Facilities"
                        });
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.GroupRequestType", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId", "RequestTypeId");

                    b.HasIndex("RequestTypeId");

                    b.ToTable("GroupRequestTypes");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            RequestTypeId = 2
                        },
                        new
                        {
                            GroupId = 2,
                            RequestTypeId = 1
                        },
                        new
                        {
                            GroupId = 3,
                            RequestTypeId = 3
                        },
                        new
                        {
                            GroupId = 4,
                            RequestTypeId = 4
                        },
                        new
                        {
                            GroupId = 4,
                            RequestTypeId = 5
                        });
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrayerId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Prayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AnsweredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PrayerDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequesterEmail")
                        .HasColumnType("TEXT");

                    b.Property<int>("StreakDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceNoteUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestTypeId");

                    b.ToTable("Prayers");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.ProgressNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MoodRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrayerId");

                    b.ToTable("ProgressNotes");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.RequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RequestTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ride"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Prayer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Supply"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Service"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Labor"
                        });
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId", "GroupId")
                        .IsUnique();

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.GroupRequestType", b =>
                {
                    b.HasOne("FaithFlow.Backend.Models.Group", "Group")
                        .WithMany("GroupRequestTypes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaithFlow.Backend.Models.RequestType", "RequestType")
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Notification", b =>
                {
                    b.HasOne("FaithFlow.Backend.Models.Prayer", "Prayer")
                        .WithMany()
                        .HasForeignKey("PrayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prayer");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Prayer", b =>
                {
                    b.HasOne("FaithFlow.Backend.Models.RequestType", "RequestType")
                        .WithMany("Prayers")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.ProgressNote", b =>
                {
                    b.HasOne("FaithFlow.Backend.Models.Prayer", "Prayer")
                        .WithMany("ProgressNotes")
                        .HasForeignKey("PrayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prayer");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.UserGroup", b =>
                {
                    b.HasOne("FaithFlow.Backend.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Group", b =>
                {
                    b.Navigation("GroupRequestTypes");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.Prayer", b =>
                {
                    b.Navigation("ProgressNotes");
                });

            modelBuilder.Entity("FaithFlow.Backend.Models.RequestType", b =>
                {
                    b.Navigation("Prayers");
                });
#pragma warning restore 612, 618
        }
    }
}
